#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Execute o lint-staged para tarefas específicas antes do commit
npx lint-staged

# Execute o Prettier para verificar e corrigir o estilo
npm run prettier:check
npm run prettier:fix

# Execute o ESLint para verificar o estilo
npm run lint:check
npm run lint:fix

npm run test